const mongoose = require('mongoose');

const gastoInversionsSchema=mongoose.Schema({
    Prestamo:{
        type:Number
    },
    Prest:{
        type:String
    },
    Org:{
        type:Number
    },
    Orgdec:{
        type:String
    },
    Edo:{
        type:Number
    },
    Edodec:{
        type:String
    },
    Cup:{
        type:String
    },
    Proyecto:{
        type:String
    },
    Estructura:{
        type:Number
    },
    Actividad:{
        type:String
    },
    NombreItem:{
        type:String
    },
    Codigog:{
        type:Number
    },
    Item:{
        type:Number
    },
    Grupo:{
        type:Number
    },
    Fuente:{
        type:String
    },
    Asiganado:{
        type:Number
    },
    Modificado:{
        type:Number
    },
    Codificado:{
        type:Number
    },
    Certificado:{
        type:Number
    },
    Comprometido:{
        type:Number
    },
    Devengado:{
        type:Number
    },
    SNcertificado:{
        type:Number
    },
    Obligaciones:{
        type:Number
    },
    SaldosMaestrias:{
        type:Number
    },
    Recaudacion:{
        type:Number
    },
    SaldosCaja:{
        type:Number
    },
    _988:{
        type:Number
    },
    Recursos:{
        type:Number
    },
    Espacio:{
        type:Number
    },
    CertificadoPlurianual:{
        type:Number
    },
    SNutilizar:{
        type:Number
    },
    Disponibles:{
        type:Number
    },
    Justificacion:{
        type:Number
    },
    Observaciones:{
        type:Number
    }
},
{colletion:'gastoInversion'})

module.exports=mongoose.model('gastoInversions',gastoInversionsSchema)