
const mongoose = require('mongoose');

                              
var rolesValidos = {
   values: ['ADMIN_ROLE', 'USER_ROLE', 'RECTOR_ROLE', 'VICERECTOR_ROLE', 'DIRECTOR_ROLE', 'PLANIFICADOR_ROLE', 
   'UPDI_ROLE', 'INACTIVO','REQUIRENTE_ROLE','PRESUPUESTO_ROLE','DIRECTOR_UPDI_ROLE','VICERECTOR_ADMINISTRATIVO_ROLE','VICERECTOR_ACADEMICO__GENERAL_ROLE' ,
   
   'IASAI_DEPARTAMENTO_DE_CIENCIAS_DE_LA_VIDA_Y_LA_AGRICULTURA_ROLE',
   'PLANIFICACION_ROLE',
   'FINANCIERO_ROLE',
   'CENTRO_DE_EDUCACION_CONTINUA_ROLE',
   'CENTRO_DE_INVESTIGACIONES_Y_APLICACIONES_MILITARES_CICTE_ROLE',
   'CIMSE_ROLE',
   //MIOS
   'SEDE_LATACUNGA_ROLE','SEDE_LATACUNGA_DEPARTAMENTOS_ROLE','SEDE_LATACUNGA_CARRERAS_ROLE','SEDE_SANTO_DOMINGO_ROLE',
   'SEDE_SANTO_DOMINGO_DEPARTAMENTOS_ROLE','SEGUIMIENTO_A_GRADUADOS_ROLE',
   'UNIDAD_DE_GESTION_DE_LA_INVESTIGACION_ROLE','UNIDAD_DE_TALENTO_HUMANO_ROLE','UNIDAD_DE_SEGURIDAD_FISICA_ROLE',
   
   'ESPE_LATACUNGA_ROLE',
   'ESPE_SANTO_DOMINGO_ROLE',
   'ADMISION_REGISTRO_ROLE',
   'VICERECTOR_INVESTIGACION_INNOVACION_ROLE',
   'GESTION_INVESTIGACION_ROLE',
   'TECNOLOGIAS_INFORMACION_COMUNICACIONES_ROLE',
   'COMUNICACION_SOCIAL_ROLE',
   'BIENESTAR_ESTUDIANTIL_ROLE',
   'BIBLIOTECA_ROLE',
   'CENTRO_DE_EDUCACIÓN_CONTINUA_ROLE',
   'UNIDAD_FINANCIERA_ROLE',
   'DESARROLLO_FISICO_ROLE',
   'DEPARTAMENTO_DE_ELECTRICA_Y_ELECTRONICA_CARRERAS_ROLE',
   'SEDE_DOMINGO_CARRERAS_ROLE',
   'EDUCACION_A_DISTANCIA_ROLE',
   'RELACIONES_DE_COOPERACION_INTERINSTITUCIONAL_ROLE',
   'DEPARTAMENTO_DE_CIENCIAS_DE_LA_TIERRA_Y_LA_CONSTRUCCION_CARRERAS_ROLE',
   'DEPARTAMENTO_DE_CIENCIAS_DE_LA_VIDA_Y_AGRICULTURA_CARRERAS_ROLE',
   'DEPARTAMENTO_DE_CIENCIAS_DE_LA_VIDA_Y_LA_AGRICULTURA_ROLE',
   'DEPARTAMENTO_DE_CIENCIAS_ECONOMICAS_ADMINISTRATIVAS_Y_DE_COMERCIO_ROLE',
   'DEPARTAMENTO_DE_CIENCIAS_ECONOMICAS_ADMINISTRATIVAS_Y_DE_COMERCIO_CARRERAS_ROLE',
   'DEPARTAMENTO_DE_CIENCIAS_HUMANAS_Y_SOCIALES_CARRERAS_ROLE', 'DEPARTAMENTO_DE_ELECTRICA_Y_ELECTRONICA_ROLE','DEPARTAMENTO_DE_ENERGIA_Y_MECANICA_CARRERAS_ROLE','DESARROLLO_EDUCATIVO_ROLE',
   'AUTOEVALUACION_Y_ASEGURAMIENTO_DE_LA_CALIDAD_ACADEMICA_ROLE', 
   'CENTRO_DE_POSGRADOS_ROLE','DESAROLLO_FISICO_ROLE','SERVICIOS_UNIVERSITARIOS_ROLE','SEGURIDAD_INTEGRADA_ROLE','EDUCACION_A_DISTACIA_ROLE',
   'INSTITUTO_DE_IDIOMAS_ROLE','CICTE_ROLE','TALENTO_HUMANO_ROLE','SECRETARIA_GENERAL_ROLE','IASA_1_ROLE','ASESORIA_JURIDICA_ROLE','CENTRO_DE_NANOCIENCIA_Y_NANOTECNOLOGIA_ROLE','SEGURIDAD_FISICA_ROLE',
   'VICERRECTORADO_ACADEMICO_GENERAL_ROLE','DEPARTAMENTO_DE_CIENCIAS_MEDICAS_ROLE','VICERRECTORADO_DE_DOCENCIA_ROLE',
   'DEPARTAMENTO_DE_CIENCIAS_HUMANAS_Y_SOCIALES_ROLE','DEPARTAMENTO_DE_CIENCIAS_DE_LA_VIDA_Y_DE_LA_AGRICULTURA_ROLE','DEPARTAMENTO_DE_CIENCIAS_DE_LA_COMPUTACION_ROLE','DEPARTAMENTO_DE_SEGURIDAD_Y_DEFENSA_ROLE',
   'DEPARTAMENTO_DE_CIENCIAS_ECONOMICAS_ADMINISTRATIVAS_DE_COMERCIO_ROLE',
   'DEPARTAMENTO_DE_CIENCIAS_DE_TIERRA_Y_LA_CONSTRUCCION_ROLE',
   'DEPARTAMENTO_DE_ENERGIA_Y_MECANICA_ROLE',
   'DEPARTAMENTO_DE_ELECTRICA_ELECTRONICA_Y_TELECOMUNICACIONES_ROLE',
   'DEPARTAMENTO_DE_CIENCIAS_EXACTAS_ROLE','PLANIFICACION_Y_DESARROLLO_INSTITUCIONAL_ROLE','TECNOLOGIAS_DE_LA_INFORMACION_Y_COMUNICACIONES_ROLE','GESTION_DE_VINCULACION_CON_LA_SOCIEDAD_ROLE',
   'LOGISTICA_ROLE'],
    message: '{VALUE} no es un rol permitido'
};


const UsuarioSchema = mongoose.Schema({

   nombre: { type: String },
   email: { type: String, required: true, unique: true },
   password: { type: String, required: true, },
   img: { type: String },
   role: {
      type: String,
      required: true,
      default: 'USER_ROLE',
      enum: rolesValidos
   },


});


/* UsuarioSchema.method('toJSON', function() {
    const { __v, _id, password, ...object } = this.toObject();
    object.uid = _id;
    return object;
})  */



module.exports = mongoose.model('Usuario', UsuarioSchema);
